---
title: "Students need support. School psychologists are here to help."
author: "Erik Reinbergs"
date: "2021-08-27"
date-modified: "2021-08-27"
categories: 
  - school psychology
---

School psychology is a broad field. Its researchers and practitioners have a wide range of training and expertise. This can make it hard to explain exactly who school psychologists are, but it’s also one of the field’s greatest strengths. And, we’re here to help.

A quick google search will tell you a lot about who school psychologists are not. We’re not school counselors, social workers, or psychiatrists — although we may work with each of these professionals. Sometimes we’re both certified school psychologists and licensed psychologists. Some school psychologists hold specialist degrees (EdS) and some hold doctorates (PhD or PsyD).

School psychologists are mental health professionals who are trained in education (particularly special education for students with disabilities) and psychology across the areas of prevention, assessment, intervention, and consultation with teachers and families. School psychologists help teachers and parents find solutions to academic, social, emotional, or behavioral challenges their children are experiencing.

In addition to working with individuals, school psychologists work to make sure the school as a whole is meeting the needs of all students. Importantly, the profession emphasizes evidence-based practices — meaning scientific research guides their decisions and actions.

With this broad training, individual school psychologists often develop deeper expertise in a particular area based on their interests and the needs of their school such as behavior supports, academic interventions, crisis, and/or mental health.

You can learn more about the field of school psychology on the website of the [National Association of School Psychologists](https://www.nasponline.org/about-school-psychology/who-are-school-psychologists?ref=ereinbergs.ghost.io).