---
title: "Advice for new grad students"
author: "Erik Reinbergs"
date: "2021-09-06"
date-modified: "2021-09-06"
categories: [academia]
---
During undergrad, I was friends with two grad students getting their PhDs in a top English program. During my junior and senior year, I started going to panels and talks about going to grad school. The one constant about these panels was that one of the grad students on the panel cried. Every time. This isn’t a pretty profession — but the same can be said of nearly every job under our current capitalist system.

It’s also an experience that can be exciting and fulfilling. (Tip 1: Embrace “both/and.”) After all, when in service of your values action that involves pain is vastly more tolerable — and can even be liberating.

Now that I’m on the “other side” of grad school (which makes me sound like a chicken that crossed the road — I’m sure there’s a metaphor for academia there somewhere…), I thought I’d share some things that helped me along the way. This post is targeted at doc students in health service psychology, public health, or similar fields that balance research and practice.

Without further ado:

*   Being both a clinician and a researcher is a monumental challenge but also a powerful gift. Academia has been called a rat race, a Ponzi scheme, self-indulgent, and an overall bad life choice. Being both a clinician and a researcher gives you an immediate connection to important whys, a leg up in communicating research (even if it’s just to your patients or trainees), and — not insignificantly — gives you an accessible and meaningful out if and when the time comes.
*   Pay attention to meta science from the very beginning. We are in a research crisis of our own making. Understanding the practices and forces that lead us here and what can be done to improve science are not really optional for the scientific enterprise as a whole and shouldn’t be optional for you as an individual. This involves building up a level of applied statistical knowledge, which is admittedly challenging — but it’s easier to be motivated to understand statistics when the background noise is, “Shit. This is wrong, has been wrong for a long time, and has had negative consequences.” As a clinician and researcher, it’s perhaps easier to know deeply the consequences of our errors.
*   Get organized yesterday. Luckily, we are a generation of researchers training with huge technological advantages. PDFs and citations are a breeze with [Zotero](https://www.zotero.org/?ref=ereinbergs.ghost.io). Accessing Google Scholar on a university network gives us access to nearly unlimited information. Cloud file storage (OneDrive, Dropbox, Google Drive, etc) means never losing your work and having automatic file versioning. Twitter puts entire networks of scientists in nearly every discipline in your pocket. Every common applied statistical problem is google-able and stats experts have usually already posted the R script somewhere online. Notes programs like [Evernote](https://evernote.com/?ref=ereinbergs.ghost.io) make everything organized and searchable — even photos of handwritten notes. If I do not write it down, I will forget it. Carrying a small notebook (shout out to [Ryder Carroll](https://medium.com/u/cd774a1bcc4c?ref=ereinbergs.ghost.io) and the [Bullet Journal](https://bulletjournal.com/?ref=ereinbergs.ghost.io) method) or quickly capturing something on my phone when I for some reason don’t have my notebook has saved me multiple times.
*   Academic unions are the best strategy currently on the table for making grad school materially survivable. But they also make the success of the larger research endeavor and ethical operation of universities more probable. The university works because you do. I benefited greatly from being part of a very strong graduate union.
*   Self care does not mean bringing yourself to the edge of self destruction and then watching Netflix. Sleep is the most important thing in your schedule. Humans cannot be okay without it.
*   A central dilemma to get comfortable with in grad school is opportunity on the one hand while overwhelm is on the other. If you’re reasonably lucky, you will get opportunities in grad school that might not ever surface again. When possible, push yourself to take them because they can be worth it. However, realize you will likely have to say no at some point to a good opportunity. Stay yourself now for that decision, because it can hurt to say no.
*   Relatedly, observe your limits. In DBT, the language of setting limits is replaced with observing limits. It’s important to observe your limits — and sometimes know that limits are stretched and that’s okay.
*   There’s a saying in the ACT therapy tradition that says, “Hold it lightly.” Academia is an environment that encourages over-identification and idealization. If you start feeling like you’re part of the Jedi Order — start finding ways to hold that script a little more lightly. This is (or at least can be) important work, but so are many of other things. Academia is a job. There are many jobs where you can be similarly in service of your values.
*   And speaking of therapy — it’s a good idea to consider the undertaking, especially if your university provides health insurance that allows you to afford it.
*   Academia is heavily political. Play the long game, and (not but) live your values. Political check-mates are deeply painful and usually supremely unjust. Even when things look like chance, remember that the house stacks its deck. A former advisor once told me that academia is not a home. I believe her.
*   Your course work — despite there being a lot of it — is not enough. Always have your own reading list of things you feel you need: Either because they’re passions or because they’re filling in gaps. Consistently doing small amounts of reading in a particular area will be a huge advantage years down the line when it comes to writing a dissertation.
*   Be clear about your narrative. What are you doing and why? How do things link together for you? Having a website with an “about me” page and a frequently updated CV has forced me to attend to this — and it has helped me personally clarify things many times. Relatedly, being a clone of your advisor isn’t the goal of grad school. Finding your niche can be a long, continually-evolving process. That’s okay.
*   The expectations of the ideal professor (or ideal graduate student) are both completely unrealistic and actually demanded by the system. Eiko Fried posted [a list of expectations](https://eiko-fried.com/are-we-asking-too-much-a-list-of-competencies-people-expect-me-to-have/?ref=ereinbergs.ghost.io) placed on him for his career stage. I wrote a similar list out for myself and it helped me see the absurdity and give myself some grace. Give yourself a break by reminding yourself that no one can be everything, no matter what or who is doing the demanding.
*   Every piece of advice and the presence of everyone above you in the academic hierarchy is subject to [survivorship bias](https://en.wikipedia.org/wiki/Survivorship_bias?ref=ereinbergs.ghost.io) — including this post. Understanding survivorship bias in both your research and in the people around you can help you sense the bigger picture.
*   Science and faith are not opposites. This has been the most important area of growth for me personally. Whether it be in capital F Faith of in the teachings of religions, faith that a better world is possible, faith that you have inherent dignity, faith that treating people well matters, faith that gives you a deeper connection with your self, faith that gives you a sense of connectedness with all living beings, faith that helps transcend the day to day, faith that keeps hope alive, etc. — remember none of this is the opposite of science.