---
title: "The country’s largest suicide prevention organization is in crisis"
author: "Erik Reinbergs"
date: "2021-08-31"
date-modified: "2021-08-31"
categories: [suicide prevention]
---
Today, members are resigning en mass from the [American Association of Suicidology](https://suicidology.org/?ref=ereinbergs.ghost.io) to protest the mishandling of the organization by a handful of board members.

The group was founded by clinical psychologist Edward Shneidman — a trailblazer in the field of suicide prevention — in 1968. For over 50 years, the organization has helped lead suicide prevention efforts in the states and fostered connections among stakeholders to ease suffering and build lives worth living.

But now, 53 years after its founding, it is in crisis due to the actions of a small number of board members. Internal political drama of organizations like this rarely make the news. But suicide prevention is a life passion of many — and a critical need for both the country and global community. Organizations like AAS provide inspiration and solace in work that brings people face to face with pain.

Although the organization has not been forthcoming in sharing details of the crisis, many of its members have learned of recent issues through people speaking out on social media and posting public letters. Two weeks ago, eight of the organization’s past presidents — all of whom are eminent figures in the field — judged the situation to be so dire that they published [a joint letter](https://www.speakingofsuicide.com/2021/08/16/american-association-of-suicidology/?ref=ereinbergs.ghost.io) asking board chair Tony Wood to resign in hopes of salvaging the situation.

The letter stated that these leaders would resign their memberships from the organization should Tony Wood not step down and encouraged other members to consider doing the same. On August 30th, the elected president of the organization, Jonathan Singer — a respected social worker and youth suicide prevention expert — also [publicly announced his resignation](https://www.speakingofsuicide.com/2021/08/30/aas-president-letter-of-resignation/?ref=ereinbergs.ghost.io) citing failures of Tony Wood’s leadership.

Today is the last day of August. Like dozens of others, today I am cancelling my membership in protest as I no longer can support the organization under the current leadership.

Where this leaves the organization is unclear. Nearly all elected leadership positions are vacant due to principled resignations. The organization today announced an [executive transition team](https://suicidology.org/2021/08/31/additional-updates/?ref=ereinbergs.ghost.io) — but it is unclear exactly what an organization in suicide prevention transitions to after many of the most prominent leading experts in the field no longer endorse it. Where professionals, loss survivors, and those with lived experience (groups that overlap more than we acknowledge) find their next home in is unclear for now.

Thanks to social media, many in the field have found connections to each other outside of the organization’s email listserv. Leaders in the field are discussing hosting a separate conference to continue the important mission of suicide prevention. Other organizations, particularly internationally, remain strong. Although the future of AAS is unclear, the work of suicide prevention and building lives worth living continues.